create or replace PROCEDURE SP_FAQ_BOARD_INSERT
(
    V_TITLE         IN  FAQ_BOARD.TITLE%TYPE,
    V_CONTENT       IN  FAQ_BOARD.CONTENT%TYPE
)
IS
BEGIN
    INSERT INTO FAQ_BOARD(F_SEQ, TITLE, CONTENT, REGDATE, READNUM)
    VALUES(SEQ_FAQ_BOARD_F_SEQ.NEXTVAL, V_TITLE, V_CONTENT,SYSDATE, 0);
    COMMIT;
END;



create or replace PROCEDURE SP_FAQ_BOARD_SELECT_ALL
(
    FAQ_RECORD      OUT     SYS_REFCURSOR
)
AS
BEGIN
    OPEN FAQ_RECORD FOR
    SELECT F_SEQ, TITLE, TO_CHAR(REGDATE, 'YYYY-MM-DD') AS REGDATE, READNUM
    FROM FAQ_BOARD
    ORDER BY F_SEQ DESC;
END;


create or replace PROCEDURE SP_FAQ_BOARD_SELECT_ONE
(
    V_F_SEQ           IN      FAQ_BOARD.F_SEQ%TYPE,
    FAQ_RECORD       OUT      SYS_REFCURSOR
)
AS
BEGIN
    OPEN FAQ_RECORD FOR
    SELECT F_SEQ, TITLE, CONTENT, TO_CHAR(REGDATE, 'YYYY-MM-DD') AS REGDATE, READNUM
    FROM FAQ_BOARD
    WHERE F_SEQ = V_F_SEQ;
END;